In [2]:
import numpy as np

In [3]:
np.pi

3.141592653589793

# 리스트와 배열

## 리스트

In [77]:
b=[3,1,4,1,5,9]

In [66]:
b[0],b[2],b[5]

(3, 4, 9)

In [76]:
len(b)
b

[3, 1, 4, 1, 5]

In [68]:
b[5]=8   #성분 바꾸기
b

[3, 1, 4, 1, 5, 8]

In [69]:
b[5]=9
b[1:4]  #1~4까지 불러오기
b.append(2) #list 성분 추가하기

In [70]:
b

[3, 1, 4, 1, 5, 9, 2]

In [63]:
b.pop()  # 맨 뒤에 있는 성분 가져오고 지우기

2

In [78]:
del b[5]  #n번째 성분 지우기
b

[3, 1, 4, 1, 5]

## array (배열)

In [91]:
a=[1,2,3,4,5,7]
b=np.array(a,int)

In [92]:
b

array([1, 2, 3, 4, 5, 7])

In [93]:
c=np.linspace(0,100,6) #linspace로 확장하고 0~100까지의 수를 6등분 해라
c

array([  0.,  20.,  40.,  60.,  80., 100.])

In [98]:
b=np.append(b,2)  #array b 에  2를 추가해라

In [99]:
b

array([1, 2, 3, 4, 5, 7, 2])

In [100]:
#같은 크기의 array 끼리 연산 가능
#np.dot(a,b) a,b 의 내적
#np.linalg.eig(b)  b의 고유값과 백터구하기
#np.linalg.inv(b) b의 역행렬

## List comprehension

In [101]:
a=[1,2,3,4,5]

In [102]:
b=[i*5 for i in a]

In [103]:
b

[5, 10, 15, 20, 25]

## 문자열 다루기

In [104]:
a='deep learning'

In [105]:
a[0],a[3]

('d', 'p')

In [107]:
b = '3.14'
c=[3,1,4]

# 입출력

In [109]:
print('aaa')

aaa


In [110]:
a=2
b=3.14

In [116]:
print(a,b)  #변수 a 와 b 출력
print('a')  #문자 a출력

2 3.14
a


In [119]:
f=open('save.txt','w')
f.write('5')
f.close()

# 함수

$$ a^b $$

In [120]:
p=1
a,b=3,5
for i in range(1,b+1):
    p = p*a

In [124]:
p

243

In [126]:
3**5

243

In [133]:
def power(a,b):
    p=1
    for i in range(1,b+1):
        p=p*a
    return p               #출력값

In [132]:
power(3,5)

243